### ISSUE TITLE
Experimental Spectra Bug

### ISSUE THREAD

**Issue by sjepeal** [zach-hartwig/ADAQAnalysis#21]
ADAQAnalysis is unable to produce an spectra (pulse area or pulse height) from waveforms data with some files

Example file is included in an email.

**Comment by zach-hartwig** [comment]
This bug seems to be due to ADAQAcquisition not properly setting the flags in the ADAQ file that specify what data actually is stored/not stored within the file. Until the upstream bug has been removed, I have commented out the code that was preventing spectra processing. This code was really intended as a nicety to the user to prevent them from being confused when no spectra was created (since there may not be waveforms within the ADAQ file).
